get_filename_component(SUBLIB ${CMAKE_CURRENT_SOURCE_DIR} NAME)
# file(GLOB SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/*.cxx")

set(SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/base.cxx
  ${CMAKE_CURRENT_SOURCE_DIR}/DeePMD.cxx
  ${CMAKE_CURRENT_SOURCE_DIR}/EAM.cxx
  ${CMAKE_CURRENT_SOURCE_DIR}/LJs-cut.cxx
  ${CMAKE_CURRENT_SOURCE_DIR}/LJs.cxx
  ${CMAKE_CURRENT_SOURCE_DIR}/maise_bpnn.cxx
  ${CMAKE_CURRENT_SOURCE_DIR}/mlip4.cxx
  ${CMAKE_CURRENT_SOURCE_DIR}/pair.cxx
)

set(${SUBLIB}_SOURCES ${SOURCES} PARENT_SCOPE)
file(GLOB HEADERS "${CMAKE_CURRENT_SOURCE_DIR}/*.h")
install(FILES ${HEADERS}
  DESTINATION include/${PROJECT_NAME}/${LIB}/${SUBLIB}
)
